name: Clang-Format Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  formatting-check:
    name: Check code formatting
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v5

    - name: Install clang-format
      run: |
        sudo apt-get update
        sudo apt-get install -y clang-format

    - name: Verify clang-format version
      run: clang-format --version

    - name: Check formatting
      run: |
        # Find all C/C++ source files and check formatting
        find Core/ lwip/app/ lwip/target/ MAX31856/max31856/ -type f \
          \( -name '*.c' -o -name '*.h' -o -name '*.cpp' -o -name '*.hpp' \) \
          -not -path '*/Drivers/*' \
          -not -path '*/src/*' \
          -print0 | while IFS= read -r -d '' file; do
          clang-format --dry-run --Werror "$file"
        done
